server:
  port: 8081  # Сессии на порту 8081

spring:
  application:
    name: session
  datasource:
    url: jdbc:postgresql://localhost:5432/movie_choice_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update  # Автоматически создаст таблицы (для разработки)
    show-sql: true      # Показывать SQL запросы в консоли
    properties:
      hibernate:
        default_schema: schema_session # Работаем только в своей схеме